### ISSUE TITLE
How i use it in Ubuntu 19.04?

### ISSUE THREAD

**Issue by liuxyon** [Soheil-ab/c2tcp#1]
I am interested in optimizing the network. I want to try to optimize for international VPN lines.

How i use it in Ubuntu 19.04 (GNU/Linux 5.0.7-050007-lowlatency x86_64) ?

**Comment by Soheil-ab** [comment]
Hi Liuxyon, 

Current Kernel-patch (the source code) requires to be prepared for the public release. That's why I haven't push it here yet. I will do that in the coming months. Then you can simply patch your desired Kernel version and use it (because TCP stack in the latest Kernel has not been changed that much compared to Kernel 4.13).

**Comment by liuxyon** [comment]
Oops, I just didn't see your reply. I have already installed the source code to ubuntu 19.0.4 Linux 5.0.10-050010-lowlatency according to your current instructions. How can I uninstall your code?

Now I mainly use the purpose of transnational very long distance network.  use for bgp router and VPN.
Currently, data from Europe to Asia often has frequent data packet loss and network jitter.

**Comment by Soheil-ab** [comment]
Liuxyon, I assume that by "...installed the source code to..." you meant that you have installed the kernel-image file from this repository. If that's the case, then simply set your previous kernel as the default kernel and reset the system. (A simple application to do that is <grub-customizer>, you can check out the instruction to install and use it at: https://github.com/Soheil-ab/C2TCP-IFIP  --> Adding C2TCP to Kernel --> Option 2: part 6).

Liuxyon, are you experiencing the packet losses when you use C2TCP or without using it? If it's with C2TCP, can you please explain your tests.

**Comment by liuxyon** [comment]
The system network doesn't know what happened several times, so I will delete it and wait for your latest kernel version.

**Comment by liuxyon** [comment]
when it is easy install and use for Linux kernel 5.2.x?

**Comment by Soheil-ab** [comment]
We are working on a more general kernel patch which will include C2TCP and a few other new designs, but I cannot give you a specific release date. You can "Watch" or "Star" the project for getting the updates.

**Comment by liuxyon** [comment]
Looking forward to your work, Mainly want to solve the problem of packet loss, high delay and slow speed in long-distance network transmission, it is can helpful use for vpn?
