### ISSUE TITLE
Any further improvement about c2tcp?

### ISSUE THREAD

**Issue by ktxu1224** [Soheil-ab/c2tcp#10]
hello, @Soheil-ab, 
I have some questions to discuss with you,
First, what about the latest research progress about c2tcp?

Second,  when apply c2tcp in cellular network, especially in 4G LTE scenario with highly bw and delay jitter, I think it is much more reasonable to adaptively update target delay according to the character of network, especially in wireless network.  So is there any research about this,  except for reinforcement learning based？

thx a lot,
Eric

**Comment by Soheil-ab** [comment]
Hi Eric,

Re your 1st question:  sorry that I cannot comment on the on going projects! :)
Re your 2nd question: If you look at section III.B.3 on our JSAC paper [here](https://ieeexplore.ieee.org/abstract/document/8638955), you will see that we define a so called Setpoint value and later in section III.D, we dynamically change the Setpoint throughout time. So, if by target delay you meant the Setpoint, C2TCP already does the adaptive update part. 

Hope that helps

**Comment by ktxu1224** [comment]
Hi, @Soheil-ab 
thx for your reply, and look forward to your latest projects!

For your 2nd reply, I means target delay from app, rather than setpoint. I understand the setpoint does the adaptive update, but it is limited by the target delay setting from specific app. Since setpoint is related with a parameter called α, which will update according to the target delay and average delay, thus delay target will affect α and further setpoint.  

A small target delay will cause a small setpoint, leading to BAD CONDITION much more frequently, further low bw utilization. A big target delay will cause buffer bloating.  Thus, how to adaptively update the target delay according to the network feature to keep delay and bw balance? Any ideas?

**Comment by Soheil-ab** [comment]
That really depends on the need of applications and the way they define their Target Delay. If **they** require a variable delay, **they** can simply change their desired delay in a live fashion (on-the-go) for C2TCP, though you may find some scenarios that the change of target delay **by** C2TCP make sense.

**Comment by ktxu1224** [comment]
Any information about changing the desired delay in a live fashion (on-the-go) for C2TCP? or is it under research?

**Comment by ktxu1224** [comment]
@Soheil-ab thx a lot, 
By the way, any information about changing the desired delay in a live fashion (on-the-go) for C2TCP? or is it under research?

**Comment by Soheil-ab** [comment]
@ktxu1224 
It is already in the code! You may wanna add a new thread and change the [target ](https://github.com/Soheil-ab/c2tcp/blob/4b5b2413543eec935144172330cd96c230294f0f/src/server-standalone.cc#L65)value dynamically during the session!

**Comment by ktxu1224** [comment]
@Soheil-ab 
ok， I get your point.
Another question, I have read the server.cc in the example, and find that you enable c2tcp and deepCC by setsockopt function. Is deepCC only used to get the tcp statictis, further to update the alpha, right? 

And, can the alpha be updated in kernel space rather than in userspace, as what you have done in server-standalone.cc? I understand the answer is YES, right?

**Comment by Soheil-ab** [comment]
@ktxu1224 
Yes & Yes!
