### ISSUE TITLE
Compiling problems with c2tcp's linux debian file

### ISSUE THREAD

**Issue by YongchangHu** [Soheil-ab/c2tcp#2]
Dear Soheil,
We have tried the new files you sent to us. The old errors have gone, though some new ones occur. Please see the following.
![20200724-172646(eSpace)](https://user-images.githubusercontent.com/3226931/88379871-325ef200-cdd6-11ea-9c7d-01efa77f329d.png)

Thank you very much for the help.
Yongchang Hu

**Comment by Soheil-ab** [comment]
Hi Yongchang,
Would you please send me (ab.soheil at gmail) a copy of your default Kernel's config file: "/usr/src/Your Default Linux Kernel/. config"

Thx

**Comment by YongchangHu** [comment]
@Soheil-ab here is the .config file you request.

[config.zip](https://github.com/Soheil-ab/c2tcp/files/4974753/config.zip)
Thanks,

Yongchang

**Comment by YongchangHu** [comment]
hi soheil,
here is the file you request.
thanks
yongchang

https://github.com/Soheil-ab/c2tcp/issues/2#issuecomment-663792536

Soheil Abbasloo <notifications@github.com> 于 2020年7月24日周五 下午9:53写道：

**Comment by Soheil-ab** [comment]
Yongchang, please install the following packages and let me know if the problem still persists:
https://drive.google.com/drive/folders/1stK9U3-evGvLI5dRvpekdw9KTMxEfFnV?usp=sharing

**Comment by YongchangHu** [comment]
@Soheil-ab Thanks for your packages and we are trying to see if it works. We will let you know ASAP.
In addition to that, we are encountered with another issue. The packages you provided are based on x86, though our testbed is likely going to be ARM-based. Although we are negotiating to see if it is possible to use x86-based instead, it might still be a long shot. Therefore, if the .patch files are ready, it will be more convenient for us to make the adaptation.  Much appreciate.
Yongchang Hu

**Comment by YongchangHu** [comment]
Still have the same issues.
![20200727-100458(eSpace)](https://user-images.githubusercontent.com/3226931/88496741-b12f7700-cff0-11ea-9570-0ec6aaabf0f6.png)
![20200727-100501(eSpace)](https://user-images.githubusercontent.com/3226931/88496749-b391d100-cff0-11ea-995b-1fd73246f189.png)

**Comment by Soheil-ab** [comment]
@YongchangHu, Seems still some drivers (related to your system) are missed. I will try to release the patch in the following weeks. Then, you can compile your Kernel regarding your desired configurations.

**Comment by YongchangHu** [comment]
@Soheil-ab Thank you very much. That will be a piece of great news for us.

**Comment by Soheil-ab** [comment]
@YongchangHu, please check out the new release including the kernel source code on master branch! Master branch includes standalone version of the server-client applications meaning you can run them directly on a real network (No need for Mahimahi). This makes it much easier for performing in-field tests. 

For the record, the JSAC release is moved to a new branch named v2.0-jsac-19. Please note that v2.0-jsac-19 branch is just for keeping the record of JSAC release and updated kernel (\*0521\*) on the master branch is not compatible with the source codes (scripts and server-client applications) on v2.0-jsac-19 branch and vice versa.
