### ISSUE TITLE
Regarding Client-Server App

### ISSUE THREAD

**Issue by limlynn** [Soheil-ab/c2tcp#3]
Hi, I want to test c2tcp with my testbed of a real network environment, not with mahimahi trace data.
My server and client device has installed with your c2tcp kernel and I was able to compile all of your scripts.

Now I want to run client and server app with my real network. 
Could you guide me on how to run your server and client app?

As I know, from your src>server.cc, I was able to find the usage 
"./server [Delay(ms)] [port] [DL-trace] [UP-trace] [log] [Target] [Initial Alpha] [qsize in pkts] [Report Period: 1 sec] "
however, if I want to run this on two different device in real network, I don't know how to set up with DL-trace / UP-trace.

and client.cc, 
"./client [server IP address] [flowid] [request data size(MB)] [dst_ip] [server port] "
what is difference between server IP address and dst_ip?

Thank you.

**Comment by Soheil-ab** [comment]
Hi @limlynn,
I have just released a new version including standalone versions of the server-client applications. You can simply use these applications to test C2TCP over a real environment (and Mahimahi). Please check out the run-sample.sh for how to use them. Basically you need to bring up the server app on the sender side first, then on the client (receiver side), you need to bring up the client app providing the server IP.

Please note that I have updated the Kernel and you need to install the new one so that you can use the standalone applications. (JSAC release still can be found on the v2.0-jsac-19 branch).

Let me know if you have any other questions.

**Comment by limlynn** [comment]
Thank you so much.

I downloaded and tried to run, I got an error with 

[server-standalone.cc-CntThread-247] CHECK KERNEL VERSION (0514+) ;CANNOT ENABLE DEEPCC Protocol not available

Do I need to reinstall the kernel? 
I have "4.13.1-c2tccp" now and follow run.sh  and run_c2tcp.sh script, except mahimahi setup.

**Comment by Soheil-ab** [comment]
@limlynn, Yes. As I mentioned, the new release requires the new Kernel. Please install the new kernel named \*0521\* located in the linux-patch folder. Then, you need to build the server-client applications (on the master branch) again in case you already have old binaries in the same project folder.

Let me know if that resolves the issue plz.

**Comment by Soheil-ab** [comment]
@limlynn, 
Just to elaborate that the scripts on the v2.0-jsac-19 branch (for example: run.sh, run_c2tcp.sh, etc.) are only compatible with the kernel \"4.13.1-c2tcp.v2.01\" (located in the linux-patch folder of the same branch) and scripts on the master branch are compatible with the kernel \"4.13.1-0521-learner\" (located in the linux-patch folder of the master branch). 

The v2.0-jsac-19 branch is just there for keeping the record of JSAC release! Master branch will carry the latest functional code.

**Comment by limlynn** [comment]
Thank you @Soheil-ab,

I'm now reinstalling kernel with  "4.13.1-0521-learner". 
My machine has "4.4.0-179-generic" as a default, so I downloaded linux-4.13.1.tar.gz first. 

After downloading linux-4.13.1.tar.gz, I followed your instruction in [https://github.com/Soheil-ab/C2TCP-IFIP]
But I used the latest patch file from the master branch. 

cd linux-4.13.1
patch -p1 < ~/c2tcp/linux-patch/linux-4-13-1-orca-c2tcp-0521.patch
sudo cp /boot/config-`uname -r` .config
sudo apt-get install libncurses5-dev
sudo make menuconfig

“Processor type and features”, then “Processor family ”. I chose the generic.
And I need to test Vegas and BBR also, so set up the advanced congestion control algorithm.

And finally, I did "sudo make"

And I've got this message,


$ sudo make
...
...
...
... 
  AR      virt/built-in.o
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  AR      init/built-in.o
  AR      built-in.o
  LD      vmlinux.o
  MODPOST vmlinux.o
net/ipv4/sysctl_net_ipv4.o:(.data+0x17c8): undefined reference to `sysctl_tcp_c2tcp_enable'
Makefile:1000: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1


Did I miss something else?
Thank you for your kind response and support.
I really appreciate all of this.

**Comment by Soheil-ab** [comment]
@limlynn, 
Maybe my instructions made a confusion, so let me elaborate on them here:

0- Having Kernel version 4.4 doesn't mean that you need to patch the kernel using the source code. You still can install 4.13.1\*0521\* directly by using the provided packages. 

1- There are two ways to install the new kernel: 
1-1) The simplest way. Install the Debian packages provided in the linux-patch folder. Start by installing linux-image-\* {sudo dpkg -i linux-image-\*0521\*} followed by installing linux-header\*0521\* . Then, use grub-customizer application (described in the README file), to bring the \"4.13.1-0521-learner\" Kernel to the top of the list, save, and reboot (That will make 4.13.1-0521 your default Kernel). Now, you have C2TCP, and all other TCP schemes such as BBR, Vegas, Cubic, etc (different TCP schemes are already included in the provided Debian packages). To verify the Kernel, execute \"uname -r\". You should see \"4.13.1-0521-learner\". 

1-2) Not that simple! If the first way went well, you are ready to start your tests. However, if you wanna modify the current Kernel source code or compile it considering enabling some specific drivers, etc. you can use the source code to patch the Kernel 4.13.1, compile it using your desired configurations, and install it later. 

(I just compiled 4.13.1 using the new patch successfully. So, there shouldn't be any problem with the second option. \'sysctl_tcp_c2tcp_enable'\ is defined in tcp_cubic.c. So, it's likely that you have excluded Cubic from the compilation (during making the config file) which made that Error. Anyway, if you really wanna go with second option, let me know. I may add a simple handy script to the repository that can automatically do the compilation and generate Debian packages).

So, plz let me know if using (1-1) doesn't resolve the issue.

**Comment by limlynn** [comment]
@Soheil-ab,

Thank you for providing details with a kind explanation. 
I checked the config file and I have excluded Cubic from the compilation.
I'll do make again and hope to succeed to install. 

Thank you so much.

**Comment by Soheil-ab** [comment]
@limlynn, I assume that you have compiled the kernel successfully. So, I close this isuue.
