### ISSUE TITLE
Have problem changing kernel to 4.13.1 in Ubuntu20.1

### ISSUE THREAD

**Issue by PeterSH6** [Soheil-ab/c2tcp#7]
I am using Ubuntu20.1 on my PC and I have been trying to change the kernel for 2 days but still can't get it through.
I have followed the README `sudo dpkg -i linux-image*521*`,`sudo dpkg -i linux-header*521*`,`sudo reboot ` and then verify the kernel but it was still 5.x. And then I followed your instructions in C2TCP-IFIP option2 step6.
After running `sudo upgrade-from-grub-legacy`, it gave me an error that `dpkg-maintscript-helper: error: environment variable DPKG_MAINTSCRIPT_NAME is required`. I have read some solution but I still couldn't understand how to solve it. 
If I skip the problem above and run the following instructions and use grub-customizer to bring the 4.13.1 at the first line and its recovery mode to the second line and reboot. It still see 5.x when verifying the kernel. I really don't know how to solve it.

I am new to this process and I would be really grateful if you can help me with these problems.

**Comment by Soheil-ab** [comment]
Hey @PeterSH6 

Before digging into the details, would you plz share the screenshot of your grub-customizer window?

**Comment by PeterSH6** [comment]
Sorry for the late response. Here is the screenshot of my grub-customizer. The Chinese in the screenshot means that: Ubuntu Advanced Mode (submenu)
![Screenshot from 2020-12-02 12-31-43](https://user-images.githubusercontent.com/43173188/100828598-748df380-349a-11eb-88cc-070da0c3dbfa.png)

**Comment by Soheil-ab** [comment]
Hey @PeterSH6 

As I expected, you haven't brought the Linux 4.13.1-0521-learner to the **top** of the list. Yours is on **3rd** row! 
Put it above the Ubuntu image, save, and then restart. After restart, perform a "uname -r". You'll see 4.13.1-0521-learner there.

**Comment by PeterSH6** [comment]
Oh Thanks! However, I try it when I enter with the **Ubuntu, Linux 4.13.1-0521-learner**,which was now in the first line, it told me that `error: kernel doesn't support EFI handover`. I can't figure out how to solve this problem. I am wondering if it's because I install Ubuntu20.1 and Windows10 on the same PC?
<img width="391" alt="截屏2020-12-02 下午4 07 56" src="https://user-images.githubusercontent.com/43173188/100845664-8da59d00-34b8-11eb-8814-de0949a61937.png">
So I choose to enter with Ubuntu(now in the third line), it turn black screen for a long time. 
Then I reboot forcefully and choose to enter with Ubuntu(in third line), it gave me a warning **in the following pictrue** and it enter the system successfully but the kernel is still 5.x.
<img width="1022" alt="截屏2020-12-02 下午4 04 57" src="https://user-images.githubusercontent.com/43173188/100845754-a7df7b00-34b8-11eb-89e2-5d248a34d262.png">

**Comment by Soheil-ab** [comment]
You see that error because during the compilation of the 4.13.1-0521-learner image, CONFIG_EFI_STUB flag was not set! 
Ok, how to resolve that? There are two options here: 

1) [Simple one] I already compiled a new kernel with EFI_STUB enabled. You can try to install the new deb image/header available on <c2tcp/linux-patch/efi-enabled-versions/> path to see if the new one resolves your issue. 

2) Another option is to compile your own version of the kernel and enable/disable the compile flags that you do/do-not want. To that end, you should use the patch file (c2tcp/linux-patch/linux-4-13-1-orca-c2tcp-0521.patch) and configure your own kernel by running <sudo make menuconfig>. You can refer to the README file of the C2TCP-IFIP repository (https://github.com/Soheil-ab/C2TCP-IFIP) for the details of this option.

**Comment by PeterSH6** [comment]
Thanks a lot !!!
I have tried your first option and download the newest version with CONFIG_EFI_STUB set. 
But unfortunately, when I enter with the first line, it seem to have some errors and automatically turn to the second line(recovery mode). Now I am stuck in the login page and my mouse and keyboard doesn't work.

**Comment by PeterSH6** [comment]
Here is the error screenshot when I enter the system using your latest kernel. Then it seems to enter the **recovery mode** and my mouse and keyboard doesn't work. The system clock is still working so I wonder this may be a lack of driver?
<img width="733" alt="截屏2020-12-02 下午6 38 40" src="https://user-images.githubusercontent.com/43173188/100862068-a79daa80-34cd-11eb-887e-334d6318ff37.png">

**Comment by Soheil-ab** [comment]
@PeterSH6 ,

Ya, it seems a driver issue. You can compile your own kernel from the source file and set all required flags regarding your HW. A handy starting point is to use the config file of an Ubuntu OS already installed on your system. You can find such a config files in this path: /boot/config-*

You can copy the config file to the kernel source directory (the destination file name should be ".config"). 

Hope that helps.
