### ISSUE TITLE
It's possible to apply the kernel patch to a newer kernel version?

### ISSUE THREAD

**Issue by fernandodiacenco** [Soheil-ab/c2tcp#9]
When trying to apply **linux-4-13-1-orca-c2tcp-0521.patch** to the Debian 10 kernel version **4.19.0-16** I get: 

    patch: **** Only garbage was found in the patch input

Is it possible to apply the patch to a newer kernel version? Or I HAVE to revert to 4.13x if I want to try C2TCP?

Thanks.

**Comment by Soheil-ab** [comment]
Hi @fernandodiacenco ,

There are two different points here: 

1) A patch file shows the differences between a reference file and a modified one. That said, applying our Kernel patch means modifying a source (Kernel) code to reflect the changes made by us. So, obviously you cannot use an arbitrary chosen base Kernel and apply our patch file to it. That means if you are going to make your own kernel (and not installing the provided Debian packages) you need 4.13.1 Kernel source code as the base.

2) Can you have a new kernel version and an old one at the same time? Yes, you can. Each time you boot your system, it uses only one Kernel. So, you can go back and forth with different Kernel versions on your system if you like.
